HairSalon/Models/Client.cs
namespace HairSalon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public string Name { get; set; }
    public int StylistId { get; set; }
    public Stylist Stylist { get; set; }
  }
}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
  public class HairSalonContext : DbContext
  {
    public DbSet<Client> Clients { get; set; }
    public DbSet<Stylist> Stylists { get; set; }

    public HairSalonContext(DbContextOptions options) : base(options) { }
  }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Stylist
  {
    public int StylistId { get; set; }
    public string Name { get; set; }
    public string Specialty { get; set; }
    public List<Client> Clients { get; set; }
  }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;

    public ClientsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Client> model = _db.Clients
                                  .Include(client => client.Stylist)
                                  .ToList();
      return View(model);
    }

    public ActionResult Details(int id)
    {
      Client thisClient = _db.Clients
                          .Include(client => client.Stylist)
                          .FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      if (client.StylistId == 0)
      {
        return RedirectToAction("Create");
      }
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;

    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Stylist thisStylist = _db.Stylists
                                  .Include(stylist => stylist.Clients)
                                  .FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }
  }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h1>Add a new client</h1>
<br>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  <br>
  @Html.TextBoxFor(model => model.Name)
  <br>
  @Html.LabelFor(model => model.Stylist)
  <br>
  @Html.DropDownList("StylistId")
  <br>
  <input type="submit" value="Add new client!" />
}

<h3>@Html.ActionLink("Back to home", "Index", "Home")</h3>

HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h1>Client Details</h1>
<br>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<br>
<h3>@Html.DisplayNameFor(model => model.Stylist): @Html.DisplayFor(model => model.Stylist.Name)</h3>
<br>
<h3>@Html.ActionLink("Back to Stylist List", "Index", "Stylists")</h3>

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;

<h1>Clients</h1>

@if (@Model.Count == 0)
{
  <h3>No clients have been added yet!</h3>
}
else
{
  <ul>
    @foreach (Client client in Model)
    {
      <li>@Html.ActionLink($"{client.Name}", "Details", new { id = client.ClientId }) | @client.Stylist.Name</li>
    }
  </ul>
}

<h3>@Html.ActionLink("Add new client", "Create")</h3>
<h3>@Html.ActionLink("Back to Home Page", "Index", "Home")</h3>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Eau Claire's Salon Management App</h1>
<br/>
<h3>Menu</h3>
<h4>@Html.ActionLink("My Stylists", "Index", "Stylists")</h4>
<h4>@Html.ActionLink("Add New Stylist", "Create", "Stylists")</h4>
<h4>@Html.ActionLink("Add New Client", "Create", "Clients")</h4>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Eau Claire's Salon</title>
    <link 
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
      crossorigin="anonymous"> 
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h1>Add a new stylist</h1>
<br>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <br>
  @Html.LabelFor(model => model.Specialty)
  @Html.TextBoxFor(model => model.Specialty)
  <br>
  <input type="submit" value="Add new stylist!" />
}
<br>
<h3>@Html.ActionLink("Show all stylists", "Index")</h3>

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist
@using HairSalon.Models

<h1>Stylist Details</h1>
<br>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h4>@Html.DisplayNameFor(model => model.Specialty): @Html.DisplayFor(model => model.Specialty)</h4>

@if (@Model.Clients.Count == 0)
{
  <h3>No clients have been added to this stylist yet</h3>
  <h3>@Html.ActionLink("Add new client", "Create", "Clients")</h3>
}
else
{
  <h3>Clients</h3>
  <ul>
    @foreach (Client client in Model.Clients)
    {
      <li>@Html.ActionLink($"{client.Name}", "Details","Clients", new { id = client.ClientId })</li>
    }
  </ul>
}

<h3>@Html.ActionLink("Back to Stylist List", "Index")</h3>
<h3>@Html.ActionLink("Back to Home Page", "Index", "Home")</h3>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
<h1>Stylists at Eau Claire's Salon</h1>
@if (Model.Count == 0)
{
  <h3>No stylists have been added yet</h3>
}
<ul>
  @foreach(Stylist stylist in Model)
  {
    <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
  }
</ul>

<h3>@Html.ActionLink("Add new stylist", "Create")</h3>
<h3>@Html.ActionLink("Back to Home Page", "Index", "Home")</h3>